# Generated by Django 4.2.23 on 2025-06-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '__first__'),
        ('accounting', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Budget Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='DRAFT', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='accounting.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'unique_together': {('organization', 'fiscal_year', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Allocated Amount')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.chartofaccounts')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='budget.budget')),
                ('period', models.ForeignKey(blank=True, help_text='Optional: Specify period for monthly/quarterly budgets', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='budget_lines', to='accounting.accountingperiod')),
            ],
            options={
                'verbose_name': 'Budget Line',
                'verbose_name_plural': 'Budget Lines',
                'unique_together': {('budget', 'account', 'period')},
            },
        ),
        migrations.CreateModel(
            name='BudgetCommitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commitment_date', models.DateField(verbose_name='Commitment Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Committed Amount')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Reference')),
                ('status', models.CharField(choices=[('COMMITTED', 'Committed'), ('INVOICED', 'Invoiced'), ('CANCELLED', 'Cancelled')], default='COMMITTED', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commitments', to='budget.budgetline')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commitments', to=settings.AUTH_USER_MODEL)),
                ('journal_entry', models.ForeignKey(blank=True, help_text='Link to the actual expense entry when invoiced', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_commitments', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Budget Commitment',
                'verbose_name_plural': 'Budget Commitments',
                'ordering': ['-commitment_date'],
            },
        ),
    ]
