# Generated by Django 4.2.28 on 2026-02-25 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_organization_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Period Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Accounting Period',
                'verbose_name_plural': 'Accounting Periods',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChartOfAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, verbose_name='Account Code')),
                ('name', models.CharField(max_length=255, verbose_name='Account Name')),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense'), ('OTHER', 'Other')], max_length=10, verbose_name='Account Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organization.organization')),
                ('parent_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_accounts', to='accounting.chartofaccounts', verbose_name='Parent Account')),
            ],
            options={
                'verbose_name': 'Chart of Accounts',
                'verbose_name_plural': 'Charts of Accounts',
                'ordering': ['code'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=10, verbose_name='Journal Code')),
                ('name', models.CharField(max_length=100, verbose_name='Journal Name')),
                ('type', models.CharField(choices=[('SALES', 'Sales'), ('PURCHASE', 'Purchase'), ('BANK', 'Bank'), ('CASH', 'Cash'), ('MISC', 'Miscellaneous'), ('OPENING', 'Opening Balance')], max_length=10, verbose_name='Journal Type')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('entry_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Entry Number')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted', models.BooleanField(db_index=True, default=False, help_text='Indicates if the entry is finalized and posted to the ledger.', verbose_name='Posted')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted At')),
                ('sync_status', models.CharField(choices=[('SYNCED', 'Synced'), ('PENDING', 'Pending Sync'), ('ERROR', 'Sync Error')], default='SYNCED', help_text='Status for offline synchronization', max_length=10, verbose_name='Sync Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='organization.organization')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries', to='accounting.accountingperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_entries', to=settings.AUTH_USER_MODEL, verbose_name='Posted By')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='Fiscal Year Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10, verbose_name='Status')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiscal_years', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Fiscal Year',
                'verbose_name_plural': 'Fiscal Years',
                'ordering': ['-start_date'],
                'unique_together': {('organization', 'start_date'), ('organization', 'end_date'), ('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Debit')),
                ('credit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Credit')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Line Description')),
                ('is_cleared', models.BooleanField(db_index=True, default=False, help_text='Indicates if this transaction has cleared the bank statement.', verbose_name='Is Cleared')),
                ('cleared_at', models.DateField(blank=True, null=True, verbose_name='Cleared At')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_lines', to='accounting.chartofaccounts')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
            ],
            options={
                'verbose_name': 'Entry Line',
                'verbose_name_plural': 'Entry Lines',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('fiscal_year', 'name'), ('fiscal_year', 'start_date')},
        ),
    ]
