# Generated by Django 4.2.23 on 2025-06-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '__first__'),
        ('accounting', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.CharField(choices=[('SUPPLIER', 'Supplier'), ('CUSTOMER', 'Customer'), ('DONOR', 'Donor'), ('EMPLOYEE', 'Employee'), ('OTHER', 'Other')], max_length=10, verbose_name='Type')),
                ('contact_info', models.TextField(blank=True, null=True, verbose_name='Contact Information')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tax ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_parties', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Third Party',
                'verbose_name_plural': 'Third Parties',
                'unique_together': {('organization', 'name', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('TRANSFER', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('OTHER', 'Other')], max_length=10, verbose_name='Payment Method')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='Associated Journal Entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashflow.thirdparty')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Amount')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CHEQUE', 'Cheque'), ('TRANSFER', 'Bank Transfer'), ('MOBILE', 'Mobile Money'), ('OTHER', 'Other')], max_length=10, verbose_name='Payment Method')),
                ('reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reference')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='Associated Journal Entry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
                ('third_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cashflow.thirdparty')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField(verbose_name='Statement Date')),
                ('statement_end_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Statement Ending Balance')),
                ('calculated_ledger_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Calculated Ledger Balance')),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Difference')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RECONCILED', 'Reconciled')], default='DRAFT', max_length=15, verbose_name='Status')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Reconciled At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='accounting.chartofaccounts')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='organization.organization')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bank Reconciliation',
                'verbose_name_plural': 'Bank Reconciliations',
                'ordering': ['-statement_date'],
                'unique_together': {('bank_account', 'statement_date')},
            },
        ),
    ]
