# Generated by Django 4.2.28 on 2026-02-25 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '__first__'),
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankreconciliation',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='bank_account',
            field=models.ForeignKey(blank=True, help_text='Default bank account for this third party if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_third_parties', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='payable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payable_third_parties', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='receivable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable_third_parties', to='accounting.chartofaccounts'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='Associated Journal Entry'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.journalentry', verbose_name='Associated Journal Entry'),
        ),
    ]
