# Generated by Django 4.2.28 on 2026-02-25 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_organization_uuid'),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepreciationMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Method Name')),
                ('calculation_logic', models.TextField(blank=True, null=True, verbose_name='Calculation Logic/Description')),
            ],
            options={
                'verbose_name': 'Depreciation Method',
                'verbose_name_plural': 'Depreciation Methods',
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('asset_code', models.CharField(max_length=50, verbose_name='Asset Code')),
                ('name', models.CharField(max_length=255, verbose_name='Asset Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('acquisition_date', models.DateField(verbose_name='Acquisition Date')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Acquisition Cost')),
                ('useful_life_years', models.PositiveIntegerField(verbose_name='Useful Life (Years)')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Salvage Value')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISPOSED', 'Disposed'), ('SOLD', 'Sold')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('disposal_date', models.DateField(blank=True, null=True, verbose_name='Disposal Date')),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accumulated_depreciation_for', to='accounting.chartofaccounts', verbose_name='Accumulated Depreciation Account')),
                ('asset_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_account_for', to='accounting.chartofaccounts', verbose_name='Asset Account')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_for', to='accounting.chartofaccounts', verbose_name='Depreciation Expense Account')),
                ('depreciation_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.depreciationmethod', verbose_name='Depreciation Method')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Fixed Asset',
                'verbose_name_plural': 'Fixed Assets',
                'ordering': ['acquisition_date'],
                'unique_together': {('organization', 'asset_code')},
            },
        ),
        migrations.CreateModel(
            name='DepreciationEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Depreciation Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Depreciation Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_entries', to='assets.fixedasset')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_source', to='accounting.journalentry', verbose_name='Associated Journal Entry')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_entries', to='accounting.accountingperiod')),
            ],
            options={
                'verbose_name': 'Depreciation Entry',
                'verbose_name_plural': 'Depreciation Entries',
                'ordering': ['-date'],
                'unique_together': {('asset', 'period')},
            },
        ),
    ]
