# Generated by Django 4.2.23 on 2025-06-19 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Report Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('BALANCE_SHEET', 'Balance Sheet'), ('INCOME_STATEMENT', 'Income Statement'), ('CASH_FLOW', 'Cash Flow Statement'), ('BUDGET_VS_ACTUAL', 'Budget vs Actual'), ('CUSTOM', 'Custom Report')], max_length=20, verbose_name='Report Type')),
                ('configuration_json', models.JSONField(blank=True, help_text='Stores structure/parameters for custom reports', null=True, verbose_name='Configuration (JSON)')),
                ('is_standard', models.BooleanField(default=False, verbose_name='Is Standard Report')),
            ],
            options={
                'verbose_name': 'Report Template',
                'verbose_name_plural': 'Report Templates',
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation_date', models.DateTimeField(auto_now_add=True, verbose_name='Generation Datetime')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Report Start Date')),
                ('end_date', models.DateField(verbose_name='Report End Date')),
                ('parameters_json', models.JSONField(blank=True, null=True, verbose_name='Parameters Used (JSON)')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/', verbose_name='Report File')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='organization.organization')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_reports', to='reporting.reporttemplate')),
            ],
            options={
                'verbose_name': 'Generated Report',
                'verbose_name_plural': 'Generated Reports',
                'ordering': ['-generation_date'],
            },
        ),
    ]
